### ISSUE TITLE
CSS Modules Problem

### ISSUE THREAD

**Issue by alvinhui** [ReactML/loader#11]
Code:

```html
<style lang="scss" module>
  .container {
    .strong {
      font-weight: bold;
    }
  }
</style>
<div className="container">
  <span className="strong">Class 样式</span>
</div>
```

Render result:

![image](https://user-images.githubusercontent.com/4392234/77384130-91c4db00-6dbf-11ea-9f38-d0047e384555.png)

No `strong` style appears to be generated.

**Comment by wssgcg1213** [comment]
fixed in !13
